package com.myspace.paymenthubee;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Institute implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.Long id;
	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;

	public Institute() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Institute(java.lang.Long id, java.lang.String name) {
		this.id = id;
		this.name = name;
	}

}