package com.myspace.paymenthubee;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("actionType")
	private java.lang.String actionType;
	@org.kie.api.definition.type.Label("createdAt")
	private java.util.Date createdAt;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;
	@org.kie.api.definition.type.Label("fspId")
	private String fspId;
	@org.kie.api.definition.type.Label("govtId")
	private String govtId;
	@org.kie.api.definition.type.Label("lastName")
	private java.lang.String lastName;
	@org.kie.api.definition.type.Label("mobileNo")
	private java.lang.String mobileNo;
	@org.kie.api.definition.type.Label("roles")
	private java.util.List<java.lang.String> roles;
	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("updatedAt")
	private java.util.Date updatedAt;
	@org.kie.api.definition.type.Label("userType")
	private java.lang.String userType;
	@org.kie.api.definition.type.Label("userid")
	private java.lang.String userid;
	@org.kie.api.definition.type.Label("username")
	private java.lang.String username;

	public UserData() {
	}

	public java.lang.String getActionType() {
		return this.actionType;
	}

	public void setActionType(java.lang.String actionType) {
		this.actionType = actionType;
	}

	public java.util.Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.util.Date createdAt) {
		this.createdAt = createdAt;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(java.lang.String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public java.util.List<java.lang.String> getRoles() {
		return this.roles;
	}

	public void setRoles(java.util.List<java.lang.String> roles) {
		this.roles = roles;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public java.lang.String getUserType() {
		return this.userType;
	}

	public void setUserType(java.lang.String userType) {
		this.userType = userType;
	}

	public java.lang.String getUserid() {
		return this.userid;
	}

	public void setUserid(java.lang.String userid) {
		this.userid = userid;
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.String getFspId() {
		return this.fspId;
	}

	public void setFspId(java.lang.String fspId) {
		this.fspId = fspId;
	}

	public java.lang.String getGovtId() {
		return this.govtId;
	}

	public void setGovtId(java.lang.String govtId) {
		this.govtId = govtId;
	}

	public UserData(java.lang.String actionType, java.util.Date createdAt,
			java.lang.String email, java.lang.String firstName,
			java.lang.String fspId, java.lang.String govtId,
			java.lang.String lastName, java.lang.String mobileNo,
			java.util.List<java.lang.String> roles, java.lang.String status,
			java.util.Date updatedAt, java.lang.String userType,
			java.lang.String userid, java.lang.String username) {
		this.actionType = actionType;
		this.createdAt = createdAt;
		this.email = email;
		this.firstName = firstName;
		this.fspId = fspId;
		this.govtId = govtId;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.roles = roles;
		this.status = status;
		this.updatedAt = updatedAt;
		this.userType = userType;
		this.userid = userid;
		this.username = username;
	}

}